[profile.default]
src = "src"
out = "out"
script = 'script'
test = 'test'
libs = ["node_modules", "lib"]
solc_version = '0.8.25'
auto_detect_solc = true
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'write', path = './deployments/31337/' },
    { access = 'read', path = './deploy-config/' },
    { access = 'read', path = './broadcast/' },
    { access = 'read', path = './forge-artifacts/' },
    { access = 'read', path = './out' },
    { access = 'read', path = './script/deploy/' },
    { access = 'read-write', path = './' },
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 132
multiline_func_header = "all"
number_underscore = "preserve"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
